spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    url: ${SPRING_DATASOURCE_URL}
    default-schema: public
    liquibase-schema: public
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

springdoc:
  show-actuator: false
  use-management-port: false
  api-docs:
    path: '/api-docs'
  swagger-ui:
    groups-order: DESC
    path: '/swagger-ui'
    disable-swagger-default-url: true
    operationsSorter: method
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true